### ISSUE TITLE
Create mash uninstaller

### ISSUE THREAD

**Issue by ya55en** [ya55en/mashmallow-0#30]
We need to be able to cleanly remove _mash_ itself, w/o removing `~/.bashrc.d/*.sh` and w/o removing any packages/recipe outcomes setup via _mash_.

A possible command would be:
```
$ mash self remove
```
This is a first step towards `mash self upgrade`, which would check for a new version and if one exists -- remove current and install the new one.

**Comment by joseph-dam** [comment]
`mash self remove` would do:
- remove mash core (the `MASH_HOME` directory);
- remove `.bashrc.d/00-mash-init.sh`;
- remove `.bashrc.d/99-mash-setup.sh`.

**Comment by joseph-dam** [comment]
Merged, closing.
