### ISSUE TITLE
Provide installer for `shfmt`

### ISSUE THREAD

**Issue by ya55en** [ya55en/mashmallow-0#33]
`shfmt` is a nice shell source code formatter distributed as a single binary.

`shfmt` repo given below [1]; the binary is available on the Releases page.

The installation would determine last version, compose a correct final URL reflecting the machine architecture and then download into the download cache. Then create `./local/opt/shfmt/` and put the versioned binary (e.g. `shfmt_v3.3.1_linux_amd64`) there. Then create a symlink in `./local/bin` named `shfmt`.

[1] shfmt repository: https://github.com/mvdan/sh
[2] shfmt homepage: https://webinstall.dev/shfmt/

**Comment by joseph-dam** [comment]
Merged to main, closing.
