### ISSUE TITLE
Do not provide wire .desktop

### ISSUE THREAD

**Issue by joseph-dam** [ya55en/mashmallow-0#43]
Wire apparently creates its own .desktop and an icon.
Investigate and if so, do not copy our .desktop and icon, but instead provoke wire to install its own.
Maybe a start and a subsequent kill would do.

**Comment by ya55en** [comment]
Wire indeed creates a `.desktop` file, on first run, located at `~/.local/share/applications/`. Looks like this:

```ini
[Desktop Entry]
Name=Wire
Comment=The most secure collaboration platform.
Exec="/home/mashuser/.local/opt/wire/Wire-3.26.2941_x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-wire-desktop
StartupWMClass=Wire
X-AppImage-Version=3.26.2941
Categories=Network;
GenericName=Secure messenger
Keywords=chat;encrypt;e2e;messenger;videocall
MimeType=x-scheme-handler/wire
Version=1.1
X-AppImage-BuildId=1uJ5g5X6ksf9VTvo9MQH75YdsQ1
X-Desktop-File-Install-Version=0.24
X-AppImage-Comment=Generated by /tmp/.mount_wire-dhLwjHs/AppRun
TryExec=/home/mashuser/.local/opt/wire/Wire-3.26.2941_x86_64.AppImage
```

**Comment by ya55en** [comment]
The following sequence may appear to be suitable for launching Wire briefly to get it set up its own `.deskop` file and an icon:

```bash
$ wire-desktop > /dev/null 2>&1 &
$ sleep 8 ; kill $(ps ax | awk '/wire-desktop/ && ! /--type=/ && ! /awk/ {print $1}')
```

Or possibly even better, provide a `.dekstop` file exactly as the one Wire generates. It may (or may not?) overwrite it, but the final effect would be the same -- Wire will have the expected entry in the app menu / app search.

**Comment by ya55en** [comment]
On the chrooted "Mate" desktop environment, Wire doesn't seem to create its own `.desktop` file. Needs to be investigated further.

**Comment by ya55en** [comment]
Done with merging #56; closing.
